services: 
  postgres: 
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - demo
    volumes:
      - demo:/var/lib/postgresql/data
  backend:
    image: yurilopesm/wannabet
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/wannabet?schema=public
    networks:
      - demo
    depends_on:
      - postgres
networks:
  demo:

volumes:
  demo: